# QoL
set -g mouse on
set -g set-clipboard on
set-option -g allow-rename off
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"

# Fix Leader
unbind C-b
set-option -g prefix C-s

#Theme setup, basic - true to tmux style w/ no plugin
set -g window-status-separator ""
set -g status-left "#{?client_prefix,#[fg=black]#[bg=white] 󰌌 #S #[fg=white]#[bg=black],#[fg=black]#[bg=green] 󰌌 #S #[fg=green]#[bg=black]}"
set -g status-right "#{prefix_highlight}#[fg=green,bg=black]#[fg=black,bg=green] %Y-%m-%d #[fg=black,bg=green]#[fg=black,bg=green] %H:%M #[fg=white,bg=green]#[fg=black,bg=white] #H "
set -g window-status-current-format "#[fg=black,bg=white] #[bg=white] #I  #W #[fg=white,bg=black]"
set -g window-status-format "#[fg=black,bg=green] #I  #W #[fg=green,bg=black]"
set -g status-style fg=white,bg=black
